HowrashokShop/Models/Busket.cs
using System;
using System.Collections.Generic;

namespace HowrashokShop.Models;

public partial class Busket
{
    public int Id { get; set; }

    public int ClientId { get; set; }

    public int ProductId { get; set; }

    public int Quantity { get; set; }

    public virtual Client Client { get; set; } = null!;

    public virtual Product Product { get; set; } = null!;
}

HowrashokShop/Controllers/BusketsController.cs
 using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HowrashokShop.Models;

namespace HowrashokShop.Controllers
{
    public class BusketsController : Controller
    {
        private HowrashokShopContext _context;

        public BusketsController(HowrashokShopContext context)
        {
            _context = context;
        }

        // GET: Buskets
        public async Task<IActionResult> Index(string login)
        {
            var howrashokShopContext = _context.Buskets.Include(b => b.Client).Include(b => b.Product);
            var productInBusketList = howrashokShopContext.Where(c => c.Client.Email == login).ToList();
            foreach (var item in productInBusketList)
            {
                item.Product.Category = _context.Categories.FirstOrDefault(c => c.Id == item.Product.CategoryId);
                item.Product.Costs = _context.Costs.Where(c => c.ProductId == item.Product.Id).ToList();
                item.Product.Photos = _context.Photos.Where(c => c.ProductId == item.Product.Id).ToList();
            }
            return View(productInBusketList);
        }
    }
}

HowrashokShop/Views/Buskets/Index.cshtml
@model IEnumerable<HowrashokShop.Models.Busket>

@{
    ViewData["Title"] = "Index";
}

@{
    Layout = "_Layout";
}

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">

<div class="content">
    @if (Model.Count() != 0)
    {
        <div class="centre">
            <form method="post">
                <button id="OrderButton" type="submit" style="width: 150%;
                                         height: 4%;
                                         margin-left: -25%;
                                         font-size: 16px; padding: 10%">
                    Оформить
                </button>
                <script src="~/js/addOrder.js"></script>
                <link rel="stylesheet" href="~/css/ButtonStyle.css" />
                <link rel="stylesheet" href="~/css/Centre.css" />
            </form>
        </div>
    }
    <div class="row mt-2 mb-5 margin_row">
        @foreach (var item in Model)
        {
            <div class="col-md-3 item">
                <a asp-action="Details" asp-route-id="@item.Id">
                    <div>
                        <img src="~/Images/@Html.DisplayFor(modelItem => item.Product.Photos.OrderBy(c => c.Id).ToList()[0].Photopath)" class="img_item" width="100%" />
                        <div class="main_in_item">
                            <p class="mainfont">@Html.DisplayFor(modelItem => item.Product.Category.Name)</p>
                            <p class="mainfont">@Html.DisplayFor(modelItem => item.Product.Cost)</p>
                        </div>
                        <p class="dopfont">@Html.DisplayFor(modelItem => item.Product.DescToShort)</p>

                        <form method="post">
                            <button id="DeleteButton" type="submit" style="margin-left: 35%;
                                         margin-right: 35%;
                                         margin-bottom: 5%;" asp-action="Delete" asp- asp-controller="Buskets" asp-route-id="@item.Id"
                            asp-route-user="@item.ClientId">
                                Удалить
                            </button>
                        </form>
                        <link rel="stylesheet" href="~/css/ButtonStyle.css" />
                    </div>
               </a>
            </div>
        }
    </div>
</div>